### ISSUE TITLE
No syntax highlighting in diffs

### ISSUE THREAD

**Issue by dpo** [josa42/atom-language-homebrew-formula#1]
Thanks for this package! I just discovered it. Samuel John's Sublime and Vim modes highlight the diff that follows `__END__`, but it seems this package doesn't. I didn't find a setting to enable that. Am I missing something?

**Comment by josa42** [comment]
@dpo You probably don't have the [language-diff](https://atom.io/packages/language-diff) package installed.

**Comment by dpo** [comment]
That does it, thanks! Would be good to list `language-diff` as a pre-requisite.
