### ISSUE TITLE
Ownership

### ISSUE THREAD

**Issue by danielbayley** [josa42/atom-language-homebrew-formula#6]
> Note: The repository is not maintained. If you would like to take over, please open an issue!

Hi @josa42, I would like to take over this repo… Would you also need to unpublish the Atom package with `apm`, so that I could then republish it?

**Comment by danielbayley** [comment]
@josa42 How about it?

**Comment by josa42** [comment]
@danielbayley Sorry, for the late response. Cool, thank you!

I'll transfer the repo to you. AFAIK the only thing you need to do is to adjust the [repository info in the package.json](https://github.com/josa42/atom-language-homebrew-formula/blob/906bbec5cbbb2e07a7ea7cdc8898f4a84a9dc14f/package.json#L9) and you should be able to publish via apm.

Let me know if it worked.

**Comment by josa42** [comment]
@danielbayley 

I cannot transfer the repo:
> danielbayley/atom-language-homebrew-formula already exists

Could you rename or remove your fork?

**Comment by danielbayley** [comment]
> Could you rename or remove your fork?

@josa42 Done. Cheers 👍
